.PHONY: clean All

All:
	@echo "----------Building project:[ Project1 - Release ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Project1.mk"
clean:
	@echo "----------Cleaning project:[ Project1 - Release ]----------"
	@cd "Project1" && "$(MAKE)" -f  "Project1.mk" clean
