.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeSolution - Debug ]----------"
	@cd "C:\Users\Aahil Seemab\Documents\CPP\Section15\ChallengeSolution" && "$(MAKE)" -f  "ChallengeSolution.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeSolution - Debug ]----------"
	@cd "C:\Users\Aahil Seemab\Documents\CPP\Section15\ChallengeSolution" && "$(MAKE)" -f  "ChallengeSolution.mk" clean
